apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ubuntu-sftp
  name: ubuntu-sftp
spec:
  ports:
  - port: 22
    protocol: TCP
    targetPort: 2222
  selector:
    app: ubuntu-sftp
status:
  loadBalancer: {}
